about/urls.py
from django.conf.urls import url
from . import views

app_name = 'about'
urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

reading/urls.py
from django.conf.urls import url
from . import views

app_name = 'reading'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
    url(r'^category/(?P<selected_category>[\w]+)', views.filteredindexview, name='category')
]

research/urls.py
from django.conf.urls import url
from . import views

app_name = 'research'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^domain/(?P<pk>[0-9]+)/$', views.DomainView.as_view(), name='domain'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.ProjectView.as_view(), name='project')
]

wuga/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^research/', include('research.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^reading/', include('reading.urls')),
    url(r'^about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.datetime_safe import datetime
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


class Whatsup(models.Model):
    description = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    time = models.DateField()

    def __str__(self):
        return self.description


class Photowall(models.Model):
    location = models.CharField(max_length=100)
    time = models.DateField()
    description = models.CharField(max_length=200)
    photo = ProcessedImageField(blank=True,
                                processors=[ResizeToFill(1170, 450)],
                                format='JPEG',
                                options={'quality': 72})

    def __str__(self):
        return self.description + " - " + self.location + " - " + str(self.time)

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import timedelta

from django.shortcuts import render
from django.utils.datetime_safe import datetime

from .models import Whatsup, Photowall


def indexview(request):
    range_start = datetime.now() - timedelta(days=100)
    photos = Photowall.objects.filter(time__gte=range_start).order_by('-time')
    news = Whatsup.objects.filter(time__gte=range_start).order_by('-time')
    context = {
        "photos": photos,
        "news": news
    }
    return render(request, 'home/index.html', context)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wuga</title>
    <link rel="icon"
      type="image/x-icon"
      href="{% static 'home/images/wuga.ico' %}" />
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="font-family: 'Gloria Hallelujah', cursive;" href="{% url 'home:index' %}">Wuga-sama!</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block research_active %}{% endblock %}"><a href="{% url 'research:index' %}">
                    <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Research</a>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="{% block reading_list %}{% endblock %}"><a href="{% url 'reading:index' %}">
                    <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>&nbsp; Reading List</a>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="{% block about_me %}{% endblock %}"><a href="{% url 'about:index' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; About Me</a>
                </li>
            </ul>
{#            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'research:index' %}">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Search</button>#}
{#            </form>#}
        </div>

    </div>
</nav>
<div class="container">
        {% block content %}
        {% endblock %}
</div>
<div class="container well-lg">
</div>
<div class="container well-lg">
</div>
 <!-- Footer -->
    <footer class="navbar-inverse navbar-fixed-bottom">
        <div class="container-fluid">
            <div class="row well-sm">
                <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weixin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Ga Wu, Mechanical and Industrial Enginnering,
                        University of Toronto 2016</p>
                </div>
            </div>
        </div>
    </footer>

</body>
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>
</html>