home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

reading/urls.py
from django.conf.urls import url
from . import views

app_name = 'reading'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
    url(r'^category/(?P<selected_category>[\w]+)', views.filteredindexview, name='category')
]

wuga/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^research/', include('research.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^reading/', include('reading.urls')),
    url(r'^about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reading/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Paper(models.Model):
    PAPER_CATEGORY = (
        ('ST', "Something"),
    )
    title = models.CharField(max_length=100)
    time = models.DateField()
    category = models.CharField(max_length=3, choices=PAPER_CATEGORY, default='DL')
    abstract = models.TextField()
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class WebPage(models.Model):
    PAGE_CATEGORY = (
        ('ST', "Something"),
    )
    PAGE_TYPE = (
        ('TT', "Tutorial"),
        ('DM', "DEMO"),
        ('NS', "NEWS"),
    )
    about = models.CharField(max_length=100)
    time = models.DateField()
    category = models.CharField(max_length=3, choices=PAGE_CATEGORY, default='DL')
    type = models.CharField(max_length=3, choices=PAGE_TYPE, default='DL')
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.about

reading/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Paper, WebPage


def indexview(request):
    papers = Paper.objects.all().order_by('time')[:5]
    webpages = WebPage.objects.all().order_by('time')[:5]
    categories = Paper.PAPER_CATEGORY
    selected_category = None
    context = {
        "papers": papers,
        "webpages": webpages,
        "categories": categories,
        "selected_category": selected_category,
    }
    return render(request, 'reading/index.html', context)


def filteredindexview(request, selected_category):
    papers = Paper.objects.filter(category=selected_category).order_by('time')[:5]
    webpages = WebPage.objects.filter(category=selected_category).order_by('time')[:5]
    categories = Paper.PAPER_CATEGORY
    context = {
        "papers": papers,
        "webpages": webpages,
        "categories": categories,
        "selected_category": selected_category,
    }
    return render(request, 'reading/index.html', context)

reading/templates/reading/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row top-buffer">
<div class="col-md-3 col-sm-3">
    <div class="well well-sm">
        <h3>
            <p class="well-sm" style="font-family: 'Anton', sans-serif;">Category</p>
        </h3>
        <div class="list-group">
            {% for category in categories %}
                {% if category.0 == selected_category %}
                    <a href="#" class="list-group-item active">
                        {{ category.1 }}
                    </a>
                {% else %}
                    <a href="{% url 'reading:category' category.0 %}" class="list-group-item">{{ category.1 }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-9 col-sm-9">
    {% if papers %}
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for paper in papers.all %}
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading{{ paper.pk }}">
                <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ paper.id }}" aria-expanded="false" aria-controls="collapse{{ paper.id }}">
                {{ paper.title }}
                </a>
                </h4>
            </div>
            {% if forloop.first %}
            <div id="collapse{{ paper.id }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading{{ paper.pk }}">
            {% else %}
            <div id="collapse{{ paper.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ paper.pk }}">
            {% endif %}
                <div class="panel-body">
                    <div class="well-sm well-transparent">
                        <div class="btn-group" role="group" aria-label="...">
                            <a class="btn btn-warning">Paper</a>
                            <a class="btn btn-success" href="{{ paper.link }}">Link</a>
                            <a class="btn btn-info">{{ paper.get_category_display }}</a>
                            <a class="btn btn-default">{{ paper.time }}</a>
                        </div>
                        <h4>
                            Abstract
                        </h4>
                        {{ paper.abstract }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
        <div class="alert alert-warning" role="alert">
            There is no paper under this reading list.
        </div>
{% endif %}

<div class="list-group">
    {% if webpages %}
        {% for webpage in webpages %}
            <ul class="list-group-item">
                <h4>{{ webpage.about }}</h4>
                <div class="btn-group" role="group" aria-label="...">
                    <a class="btn btn-warning">Web Page</a>
                    <a class="btn btn-success" href="{{ webpage.link }}">Link</a>
                    <a class="btn btn-info">{{ webpage.get_category_display }}</a>
                    <a class="btn btn-info">{{ webpage.get_type_display }}</a>
                    <a class="btn btn-default">{{ webpage.time }}</a>
                </div>
            </ul>
        {% endfor %}
    {% else %}
        <div class="alert alert-warning" role="alert">
        There is no webpage to share under this reading list!
        </div>
    {% endif %}
</div>

</div>
</div>
{% endblock %}