home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

research/urls.py
from django.conf.urls import url
from . import views

app_name = 'research'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^domain/(?P<pk>[0-9]+)/$', views.DomainView.as_view(), name='domain'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.ProjectView.as_view(), name='project')
]

wuga/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^research/', include('research.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^reading/', include('reading.urls')),
    url(r'^about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

research/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from markdownx.models import MarkdownxField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from markdownx.utils import markdownify


class Domain(models.Model):
    domain_name = models.CharField(max_length=100)
    domain_logo = ProcessedImageField(blank=True,
                                      processors=[ResizeToFill(300, 300)],
                                      format='JPEG',
                                      options={'quality': 60})

    def __str__(self):
        return self.domain_name


class Project(models.Model):
    PROJECT_CATEGORY = (
        ('ST', "Something"),
    )
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=100)
    project_type = models.CharField(max_length=3, choices=PROJECT_CATEGORY, default='RD')
    project_short_description = models.CharField(max_length=200)
    project_long_description = MarkdownxField()

    # Create a property that returns the markdown instead
    @property
    def formatted_long_description(self):
        return markdownify(self.project_long_description)

    def __str__(self):
        return self.project_name

research/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic
from .models import Domain, Project


class IndexView(generic.ListView):
    template_name = 'research/index.html'
    context_object_name = 'domain_list'

    def get_queryset(self):
        """Return all domains"""
        return Domain.objects.all()


class DomainView(generic.DetailView):
    model = Domain
    template_name = 'research/domain.html'


class ProjectView(generic.DetailView):
    model = Project
    template_name = 'research/detail.html'

research/templates/research/detail.html
{% extends "base.html" %}
{% block content %}
<div class="well well-sm">
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">{{ project.project_name }}</h1>
    <p class="lead blog-description">{{ project.project_short_description }}</p>
  </div>
</div>
<div class="container">
      <div class="row">
        <div class="col-sm-9 blog-main">
            {{ project.formatted_long_description|safe }}
        </div>
          <div class="col-sm-2 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
              <h4>Tags</h4>
              <p>
                  ...
              </p>
          </div>
      </div>
      </div>
</div>
</div>
{% endblock %}

research/templates/research/domain.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col-sm-3 col-md-3 well-sm">
        <div class="thumbnail">
            <img src={{ domain.domain_logo.url }} alt="...">
            <div class="caption">
            <h3 style="font-family: 'Anton', sans-serif;">{{ domain.domain_name }}</h3>
            </div>
        </div>
    </div>
    <div class="col-sm-9 col-md-9 well-sm">
        <div class="panel panel-default">
            <div class="panel-heading">Projects</div>
            <div class="panel-body">
            {% if domain.project_set.all %}
            <ul class="media-list">
                {% for project in domain.project_set.all %}
                    <li class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="{% url 'research:project' project.id %}" >{{ project.project_name }}</a>
                        </h4>
                        <p>{{ project.project_short_description }}</p>
                    </div>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <p>There is no project under this research topic!</p>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

research/templates/research/index.html
{% extends "base.html" %}
{% block content %}
    <div class="well-sm">
    {% if domain_list %}
        <div class="row">
        {% for domain in domain_list %}
          <div class="col-sm-4 col-md-4">
            <div class="thumbnail">
              <img src={{ domain.domain_logo.url }} alt="...">
              <div class="caption">
                <h3 style="font-family: 'Anton', sans-serif;">{{ domain.domain_name }}</h3>
                <p><a href="{% url 'research:domain' domain.id %}" class="btn btn-primary" role="button">See Detail</a>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert"> Hi, glad you are here. </div>
        <div class="alert alert-warning" role="alert"> There is no content under this sub-branch, please add them through admin management.</div>
    {% endif %}
    </div>
{% endblock %}