about/urls.py
from django.conf.urls import url
from . import views

app_name = 'about'
urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

wuga/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^research/', include('research.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^reading/', include('reading.urls')),
    url(r'^about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class Profile(models.Model):
    name = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    email = models.EmailField()
    phone_regex = RegexValidator(regex=r'^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$',
                                 message="Need Valid Phone Number")
    phone = models.CharField(max_length=15, validators=[phone_regex], blank=True)
    address = models.CharField(max_length=200)
    photo = ProcessedImageField(blank=False,
                                      processors=[ResizeToFill(300, 400)],
                                      format='JPEG',
                                      options={'quality': 60})
    biography = MarkdownxField(blank=True)

    # Create a property that returns the markdown instead
    @property
    def formatted_biography(self):
        return markdownify(self.biography)

    def __str__(self):
        return self.name + ' - ' + self.email


class Publication(models.Model):
    PUBLICATION_CATEGORY = (
        ('AAAI', "Association for the Advancement of Artificial Intelligence (AAAI)"),
        ('NIPS', "Neural Information Processing Systems (NIPS)"),
        ('IJCAI', "International Joint Conference on Artificial Intelligence (IJCAI)"),
        ('ICML', "International Conference on Machine Learning (ICML)"),
        ('ARXIV', "ArXiv- Waiting to Publish")
    )
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    time = models.DateField()
    coauthors = models.CharField(max_length=100, blank=True)
    publisher = models.CharField(max_length=10, choices=PUBLICATION_CATEGORY, default='AAAI')
    paper_link = models.CharField(max_length=200)
    code_link = models.CharField(max_length=200, blank=True)
    presentation_link = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from .models import Profile


def indexview(request):
    profiles = Profile.objects.all()
    context = {
        "profiles": profiles,
    }
    return render(request, 'about/index.html', context)

about/templates/about/index.html
{% extends 'base.html' %}
{% block content %}
{% if profiles %}
    <div class="row">
{% for profile in profiles %}
    <div class="col-sm-4 col-md-4 col-lg-3 well-sm">
    <div class="thumbnail">
        <img src="{{ profile.photo.url }}">
        <div class="caption well-sm">
            <address>
              <strong>{{ profile.occupation }}</strong><br>
              {{ profile.address }}<br>
              <abbr title="Phone">P:</abbr> {{ profile.phone }}
            </address>

            <address>
              <strong>{{ profile.name }}</strong><br>
              <a href="mailto:{{ profile.email }}">{{ profile.email }}</a>
            </address>
        </div>
    </div>
    </div>
    <div class="col-sm-8 col-md-8 col-lg-9 well-sm">
        <div class="well">
            {{ profile.formatted_biography|safe }}
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Publications</div>

                <div class="list-group">
                    {% if profile.publication_set %}
                        {% for publication in profile.publication_set.all %}
                            <ul class="list-group-item">
                                <h4>{{ publication.title }}</h4>
                                <h5>Publisher: {{ publication.get_publisher_display }}</h5>
                                <h5>Coauthors: {{ publication.coauthors }}</h5>
                                <div class="btn-group" role="group" aria-label="...">
                                    <a class="btn btn-success" href="{{ publication.paper_link }}">Link</a>
                                    <a class="btn btn-primary" href="{{ publication.code_link }}">Code</a>
                                    <a class="btn btn-info" href="{{ publication.presentation_link }}">Slides</a>
                                    <a class="btn btn-default">{{ publication.time.year }}</a>
                                </div>
                            </ul>
                        {% endfor %}
                    {% else %}
                        <p>There is no webpage to share under this reading list!</p>
                    {% endif %}
                </div>

        </div>
    </div>
{% endfor %}
    </div>
{% else %}
<div class="alert alert-danger" role="alert">
    Oh shit! we are not able to find your profile, if you didn't upload, please upload it through admin management.
</div>
{% endif %}
{% endblock %}